# This file is part of the visdriver project.
#
# Copyright (c) 2023 Sebastian Pipping <sebastian@pipping.org>
#
# visdriver is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# visdriver is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along
# with visdriver. If not, see <https://www.gnu.org/licenses/>.

name: Build on Windows

# Drop permissions to minimum, for security
permissions:
  contents: read

on:
  pull_request:
  push:
  schedule:
    - cron: '0 2 * * 5'  # Every Friday at 2am
  workflow_dispatch:

jobs:
  windows-msvc:
    name: Build on Windows
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:

    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

    - name: Configure
      run: |-
        cmake \
          -G "Visual Studio 17 2022" \
          -A Win32 \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -S . \
          -B build

    - name: Make
      run: |-
        cmake --build build/

    - name: Prepare build artifacts for upload
      run: |-
        mkdir "visdriver_win32bin_msvc_${{ github.sha }}"
        cp -v \
          COPYING \
          README.md \
          build/Debug/visdriver.exe \
          "visdriver_win32bin_msvc_${{ github.sha }}"/

    - name: Upload build artifacts
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08  # v4.6.0
      with:
        name: "visdriver_win32bin_msvc_${{ github.sha }}"
        path: "visdriver_win32bin_msvc_${{ github.sha }}/"
        if-no-files-found: error
